In [ ]:
import torch
print(torch.__version__)
!pip install torch-scatter torch-sparse -f https://data.pyg.org/whl/torch-{torch.__version__}.html

1.12.0+cu113
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://data.pyg.org/whl/torch-1.12.0+cu113.html
     |████████████████████████████████| 7.9 MB 5.4 MB/s 
     |████████████████████████████████| 3.5 MB 36.8 MB/s 


In [ ]:
pip install torchvision

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
pip install git+https://github.com/pyg-team/pytorch_geometric.git#egg=torch-geometric[full]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/pyg-team/pytorch_geometric.git to /tmp/pip-install-_xaih609/torch-geometric_a5ed7534868b45e99146ff3944a2e99e
  Running command git clone -q https://github.com/pyg-team/pytorch_geometric.git /tmp/pip-install-_xaih609/torch-geometric_a5ed7534868b45e99146ff3944a2e99e
     |████████████████████████████████| 151 kB 5.2 MB/s 
     |████████████████████████████████| 585 kB 8.7 MB/s 
     |████████████████████████████████| 1.4 MB 45.2 MB/s 
     |████████████████████████████████| 500 kB 48.9 MB/s 
     |████████████████████████████████| 660 kB 44.7 MB/s 
     |████████████████████████████████| 93 kB 1.4 MB/s 
     |████████████████████████████████| 419 kB 45.4 MB/s 
     |████████████████████████████████| 596 kB 41.2 MB/s 
     |████████████████████████████████| 141 kB 46.1 MB/s 
     |████████████████████████████████| 117 kB 47.0 MB/s 
     |█████████████████████████

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
import sklearn.metrics as metrics


import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense, Dropout
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.preprocessing import StandardScaler
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import ipywidgets as widgets 
from IPython.display import display 
import pylab
from sklearn.compose import ColumnTransformer
import sklearn
import keras.layers as kl
from numpy import genfromtxt
from numpy import asarray
from numpy import savetxt
import networkx as nx


import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv
from torch_geometric.nn import SAGEConv
from torch_geometric.nn import GCN

In [ ]:
from torch_geometric.data import InMemoryDataset, Data, download_url, extract_zip

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
df_arsenic_prelim = pd.read_csv (r'drive/My Drive/Colab Notebooks/as.csv')
correlation_matrix_recovered = genfromtxt('drive/My Drive/Colab Notebooks/PC.csv',delimiter=',')
euclidean_matrix_recovered = genfromtxt('drive/My Drive/Colab Notebooks/ED.csv',delimiter=',')

In [ ]:
df_arsenic_prelim

SiteID    As  X_Albers   Y_Albers   WellDepth  AvgAnnualN_CAFO_1992_97  \
0           1   6.0  924000.0  2006000.0  105.912831                16.678065   
1           2   1.0  892000.0  2080000.0   54.861323                 7.688502   
2           3  13.0  886000.0  2066000.0   34.745504                 6.245885   
3           4   1.0  898000.0  2076000.0   59.737885                 4.900404   
4           5   2.0  896000.0  2062000.0   45.717769                 6.511748   
...       ...   ...       ...        ...         ...                      ...   
9996     9997   0.0  536000.0  2390000.0   35.964645                 3.949343   
9997     9998   1.0  610000.0  2484000.0   19.506248                 8.030330   
9998     9999   6.0  616000.0  2526000.0   24.992380                 0.158934   
9999    10000   0.0  602000.0  2586000.0   26.211521                 0.004975   
10000   10001   0.0  668000.0  2620000.0   12.496190                 0.028986   

       AvgAnnualN_Fert_1992_2001       AWC     AWS25   BFI  ...   Transmiss  \
0                      48.483771  0.141277  5.384314  21.0  ...  143.362904   
1                      50.638261  0.217775  7.311919  37.0  ...  137.152244   
2                      43.503552  0.140200  5.400000  33.0  ...  121.646066   
3                      34.132068  0.154753  5.318469  37.0  ...  298.232568   
4                      45.355325  0.140200  5.400000  28.0  ...   97.123320   
...                          ...       ...       ...   ...  ...         ...   
9996                   11.546021  0.082813  2.720000  74.0  ...   54.346575   
9997                   10.843744  0.159466  4.090000  59.0  ...  115.224598   
9998                    0.199489  0.126106  4.030000  63.0  ...   40.882361   
9999                    0.015434  0.126106  4.030000  66.0  ...   59.112810   
10000                   0.058744  0.066700  2.000000  62.0  ...   59.639661   

             TWI        VRT       VWC  YngWtrMeanAge  YngWtrMeanAge_VertMean  \
0       9.902970   5.956547  0.304000      23.158235               17.689265   
1       9.067347   4.196766  0.343552      22.015855               17.739371   
2      11.470297  17.558480  0.270166      17.762669               15.950136   
3       9.815662   1.231952  0.328985      27.709500               17.589893   
4       9.435353  21.539828  0.268193      19.238581               14.557619   
...          ...        ...       ...            ...                     ...   
9996    8.505940   6.354813  0.160139      14.421028               10.310266   
9997   13.790910   0.416030  0.344196       8.765928               16.686542   
9998   11.154347   1.048951  0.253424      15.627269               11.281490   
9999   13.113131   0.520421  0.280687      21.815356               15.832110   
10000  12.550000   0.098656  0.367925       5.079691               14.141643   

             DTW   Data  as10  Pred  
0       3.082386  train   0.0  0.00  
1       3.076582  train   0.0  0.06  
2       5.645093  train   1.0  0.83  
3       1.044807  train   0.0  0.03  
4       8.535328  train   0.0  0.01  
...          ...    ...   ...   ...  
9996   11.500084   test   0.0  0.00  
9997    0.188501   test   0.0  0.11  
9998    1.518130   test   0.0  0.01  
9999    0.643534   test   0.0  0.05  
10000   0.114506   test   0.0  0.01  

[7616 rows x 87 columns]

In [ ]:
df_arsenic_prelim.isnull().values.any()
df_arsenic_prelim.isnull().sum()
df_arsenic_prelim = df_arsenic_prelim.dropna()

In [ ]:
X = df_arsenic_prelim.iloc[:,4:-3]
Y_TRUE = df_arsenic_prelim.iloc[:,1]
Y_PRED_BIN = df_arsenic_prelim.iloc[:,-2]
Y_PRED_CONTINUOUS = df_arsenic_prelim.iloc[:,-1]

In [ ]:
mockx= np.array(X)
mocky= np.array(Y_TRUE)
print("Shape of mockx",mockx.shape)
print("Shape of mockx",mocky.shape)

Shape of mockx (7616, 80)
Shape of mockx (7616,)


array([ 6.,  1., 13., ...,  6.,  0.,  0.])

In [ ]:
tensor_x = torch.from_numpy(mockx)
tensor_y = torch.from_numpy(mocky)
tensor_y

tensor([ 6.,  1., 13.,  ...,  6.,  0.,  0.], dtype=torch.float64)

In [ ]:
train_mask = np.ones(7616)
test_mask = np.zeros(7616)
val_mask = np.zeros(7616)
tensor_train_mask = torch.tensor(train_mask, dtype=torch.long)
tensor_val_mask = torch.tensor(val_mask, dtype=torch.long)
tensor_test_mask = torch.tensor(test_mask, dtype=torch.long)

In [ ]:
print("the Minimum Euclidean distance obtained is: ",np.min(euclidean_matrix_recovered))
print("the Maximum Euclidean distance obtained is: ",np.max(euclidean_matrix_recovered))
print("ED shape",euclidean_matrix_recovered.shape)

num=0
x=y=7616
cutoff_euclidean = 10000
cutoff_correlation = 0.95
Edge_matrix = np.zeros((x,y))
Edge_matrix_coo = np.zeros((2,76811*2))

for i in range(x):
    for j in range(y):
        if (i!=j) and (correlation_matrix_recovered[i,j] > cutoff_correlation or euclidean_matrix_recovered[i,j] < cutoff_euclidean):
            Edge_matrix[i,j]=1
            num+=1
print(num)

In [ ]:
G = nx.from_numpy_matrix(Edge_matrix)
n = G.number_of_nodes()
m = G.number_of_edges()
print(m,n)

edge_list = np.zeros((2,m))

edge_list[0,:] = nx.to_pandas_edgelist(G)['source']
edge_list[1,:] = nx.to_pandas_edgelist(G)['target']

10469 7616


In [ ]:
#edge_list = torch.from_numpy(edge_list)
edge_idx = torch.tensor(edge_list, dtype=torch.long)

In [ ]:
Trial1data = Data(x=tensor_x,edge_index=edge_idx,y=tensor_y,train_mask=tensor_train_mask,val_mask=tensor_val_mask,test_mask=tensor_test_mask)

In [ ]:
data.y

In [ ]:
Trial1data

Data(x=[7616, 80], edge_index=[2, 10469], y=[7616])

In [ ]:
global hidden_layer_dimension
hidden_layer_dimension = 100

class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        # you can change convolutions here 
        #self.conv1 = GCN(80, hidden_layer_dimension,num_layers=5)
        #self.conv2 = GCN(hidden_layer_dimension,10,num_layers=5)
       
        self.conv1 = GCNConv(dataset.num_node_features, hidden_layer_dimension)
        self.conv2 = GCNConv(16, dataset.num_classes)
        self.dense = nn.LazyLinear(1)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = self.conv1(x, edge_index)
        x = F.selu(x)
        #x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)
        x = F.selu(x)
        x = self.dense(x)
        return x

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Net().to(device)
data = Trial1data.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)

model.train()
for epoch in range(10000):
    optimizer.zero_grad()
    data['x'] = data['x'].float()
    out = model(data)
    loss = F.mse_loss(out[data.train_mask], data.y[data.train_mask].float())
    loss.backward()
    optimizer.step()
    
    pred = model(data)
    #correct = float (pred[data.train_mask] - (data.y[data.train_mask]).sum())
    #acc = correct / data.train_mask.sum().item()
    print('Epoch: %d, mse: %.8f'%(epoch,loss))

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: UserWarning: Using a target size (torch.Size([7616])) that is different to the input size (torch.Size([7616, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  # This is added back by InteractiveShellApp.init_path()


Epoch: 0, mse: 25315.61914062
Epoch: 1, mse: 232932.00000000
Epoch: 2, mse: 6907.81152344
Epoch: 3, mse: 3944.78149414
Epoch: 4, mse: 1323.22644043
Epoch: 5, mse: 476.84317017
Epoch: 6, mse: 3679.25000000
Epoch: 7, mse: 6040.35595703
Epoch: 8, mse: 3252.70849609
Epoch: 9, mse: 821.44927979
Epoch: 10, mse: 148.87403870
Epoch: 11, mse: 5.14837551
Epoch: 12, mse: 28.12781143
Epoch: 13, mse: 98.60840607
Epoch: 14, mse: 92.55858612
Epoch: 15, mse: 231.21290588
Epoch: 16, mse: 87.47313690
Epoch: 17, mse: 148.87889099
Epoch: 18, mse: 137.97668457
Epoch: 19, mse: 61.26586533
Epoch: 20, mse: 3.84344530
Epoch: 21, mse: 1.86843896
Epoch: 22, mse: 2646.43872070
Epoch: 23, mse: 1.85079193
Epoch: 24, mse: 0.60873789
Epoch: 25, mse: 0.21480845
Epoch: 26, mse: 2.25946045
Epoch: 27, mse: 1.80438781
Epoch: 28, mse: 1.90936494
Epoch: 29, mse: 229.58888245
Epoch: 30, mse: 1.77566791
Epoch: 31, mse: 1.76637006
Epoch: 32, mse: 1.75639093
Epoch: 33, mse: 1.74583685
Epoch: 34, mse: 1.73479974
Epoch: 35, mse: 

KeyboardInterrupt: ignored

In [ ]:
 _, pred = model(data).max(dim=1)
correct = float (pred[data.test_mask].eq(data.y[data.test_mask]).sum().item())
acc = correct / data.test_mask.sum().item()
print('Accuracy: {:.4f}'.format(acc))

In [ ]:
pred

tensor([[0.9959],
        [0.9959],
        [0.9959],
        ...,
        [0.9959],
        [0.9959],
        [0.9959]], grad_fn=<AddmmBackward0>)

In [ ]:
data.y

tensor([ 6.,  1., 13.,  ...,  6.,  0.,  0.], dtype=torch.float64)

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Net().to(device)
data = Trial1data.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)

model.train()
for epoch in range(10000):
    optimizer.zero_grad()
    data['x'] = data['x'].float()
    out = model(data)
    loss = F.mse_loss(out[data.train_mask], data.y[data.train_mask].float())
    loss.backward()
    optimizer.step()
    
    pred = model(data)
    #correct = float (pred[data.train_mask] - (data.y[data.train_mask]).sum())
    #acc = correct / data.train_mask.sum().item()
    print('Epoch: %d, mse: %.4f'%(epoch,loss))

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: UserWarning: Using a target size (torch.Size([7616])) that is different to the input size (torch.Size([7616, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  # This is added back by InteractiveShellApp.init_path()


Epoch: 0, mse: 170629.9062
Epoch: 1, mse: 16118.3750
Epoch: 2, mse: 86667.5156
Epoch: 3, mse: 714.3786
Epoch: 4, mse: 1.0964
Epoch: 5, mse: 733.8629
Epoch: 6, mse: 1.0444
Epoch: 7, mse: 1.0215
Epoch: 8, mse: 0.9999
Epoch: 9, mse: 0.9787
Epoch: 10, mse: 0.9579
Epoch: 11, mse: 0.9375
Epoch: 12, mse: 0.9171
Epoch: 13, mse: 0.8968
Epoch: 14, mse: 0.8764
Epoch: 15, mse: 0.8556
Epoch: 16, mse: 0.8347
Epoch: 17, mse: 0.8135
Epoch: 18, mse: 0.7919
Epoch: 19, mse: 0.7700
Epoch: 20, mse: 0.7477
Epoch: 21, mse: 305.3626
Epoch: 22, mse: 0.7031
Epoch: 23, mse: 0.6811
Epoch: 24, mse: 0.6589
Epoch: 25, mse: 0.6363
Epoch: 26, mse: 0.6133
Epoch: 27, mse: 0.5898
Epoch: 28, mse: 0.0598
Epoch: 29, mse: 0.0565
Epoch: 30, mse: 0.0567
Epoch: 31, mse: 23.5726
Epoch: 32, mse: 0.4916
Epoch: 33, mse: 0.4760
Epoch: 34, mse: 0.4591
Epoch: 35, mse: 0.4412
Epoch: 36, mse: 0.4225
Epoch: 37, mse: 0.4030
Epoch: 38, mse: 0.3831
Epoch: 39, mse: 0.3628
Epoch: 40, mse: 0.3422
Epoch: 41, mse: 0.3215
Epoch: 42, mse: 0.3009
E

KeyboardInterrupt: ignored

tensor([[0.9996],
        [0.9996],
        [0.9996],
        ...,
        [0.9996],
        [0.9996],
        [0.9996]], grad_fn=<AddmmBackward0>)